# Generated by Django 3.0.2 on 2020-01-21 19:51

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200121_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(upload_to='resources/images/', verbose_name='Image'),
        ),
    ]
