# Generated by Django 3.0.2 on 2020-01-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20200123_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='src',
        ),
    ]
