# Generated by Django 3.0.2 on 2020-01-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20200124_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
