# Generated by Django 3.0.2 on 2020-01-24 11:31

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20200124_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=versatileimagefield.fields.VersatileImageField(height_field=models.PositiveIntegerField(), upload_to='images/', verbose_name='Image', width_field=models.PositiveIntegerField()),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(),
        ),
    ]
