language: go
sudo: false
go:
  - 1.13.1
  - tip

env:
  GO111MODULE=on

script:
  - go mod download
  - go test -v -race -covermode=atomic -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - curl -sL https://git.io/goreleaser | bash
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - dist/clickhouse-bulk-*.zip
    - dist/clickhouse-bulk-*.tar.bz2
    - dist/clickhouse-bulk-*.sha256
  skip_cleanup: true
  on:
    tags: true
    repo: nikepan/clickhouse-bulk
    condition: $TRAVIS_GO_VERSION =~ ^1\.13\.[0-9]+$
