# Generated by Django 3.0.2 on 2020-01-21 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20200121_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
