# Generated by Django 3.0.2 on 2020-01-23 10:03

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20200121_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image'),
        ),
    ]
